// GENERATED by sync-constants — não editar manualmente (fonte: tabela ui_labels).
// Renomear = editar a linha no Supabase (colunas name_*/tooltip_*) e rodar `npm run sync-constants`.
// LABELS.<field> = { full, short, abbrev, tooltip_full, tooltip_short }. field = nome da variável.
export const LABELS = {
  decision: { full: "Prioridade de leitura", short: "Prioridade", abbrev: "Prior.", tooltip_full: "Quão provável que você goste — número único (0–10) pra priorizar o que ler primeiro. Ancorado na Nota Prevista (que já embute o Alinhamento) e ajustado pelo Veredito IA quando existe. É PRIORIDADE, não previsão de nota.", tooltip_short: "Número pra priorizar o que ler primeiro (não é previsão de nota)." },
  expected_score: { full: "Nota Prevista", short: "N. Prevista", abbrev: "N. Prev.", tooltip_full: "Nota que o modelo prevê que você daria à obra (0–10). É a âncora calibrada — uma regressão Ridge treinada nas suas notas.", tooltip_short: "Nota que o modelo prevê que você daria (0–10)." },
  calc_score: { full: "Nota Calculada", short: "Nota Calc.", abbrev: "N. Calc", tooltip_full: "Nota determinística de ensemble — âncora interna do preditor, não é a nota headline.", tooltip_short: "Âncora interna do preditor." },
  personal_fit: { full: "Alinhamento", short: "Alinhamento", abbrev: "Alinh.", tooltip_full: "O quanto a obra combina com seu perfil de gosto, como percentil na sua biblioteca (0–100; Top 25% = ≥75). Junta tags amadas/evitadas, faixas ideais de critério e consistência geral.", tooltip_short: "O quanto a obra combina com seu perfil (percentil 0–100)." },
  platform_avg: { full: "Média externa", short: "N. Externa", abbrev: "N. Ext.", tooltip_full: "Média ponderada das notas das plataformas externas (AniList, MAL, etc.), 0–10. Pondera mais as fontes com mais votos.", tooltip_short: "Média ponderada das notas externas (0–10)." },
  total_votes: { full: "Votos externos", short: "Votos", abbrev: "Votos", tooltip_full: "Total de votos/avaliações somados nas plataformas externas. Quanto maior, mais confiável é a Nota.M.", tooltip_short: "Total de votos nas plataformas externas." },
  alignment_score: { full: "Veredito IA", short: "Veredito", abbrev: "Ver.", tooltip_full: "Veredito do consultor IA (0–100), gerado sob demanda. Reordena as recomendações e ajusta a Prioridade — a maioria das obras fica sem valor até passar pelo Rankear.", tooltip_short: "Veredito do consultor IA (0–100)." },
  synopsis_q: { full: "Interesse na obra", short: "Interesse", abbrev: "Int.", tooltip_full: "O quanto a obra te interessou (♥ a ♥♥♥♥), informado por você na triagem/avaliação.", tooltip_short: "Seu interesse informado (♥ a ♥♥♥♥)." },
  synopsis_pred: { full: "Interesse na obra previsto", short: "Interesse previsto", abbrev: "Int. Prev.", tooltip_full: "Previsão da IA de quanto a obra vai te interessar (♥ a ♥♥♥♥), com base no seu perfil. Diferente de \"Interesse na obra (user)\", que é o que você informou. Só na feature Paga.", tooltip_short: "Previsão da IA do seu interesse (♥ a ♥♥♥♥)." },
  fav: { full: "Favorito", short: "Favorito", abbrev: "Fav.", tooltip_full: "Indica se a obra está marcada como favorita.", tooltip_short: "Marcada como favorita." },
  title: { full: "Título", short: "Título", abbrev: "Título", tooltip_full: "", tooltip_short: "" },
  publication_status: { full: "Status de publicação", short: "Publicação", abbrev: "Pub.", tooltip_full: "Status de publicação da obra na fonte (em andamento, concluída, hiato, cancelada).", tooltip_short: "Status de publicação na fonte." },
  personal_status: { full: "Status pessoal", short: "Status pessoal", abbrev: "Status", tooltip_full: "Seu status de leitura para a obra (pra ler, lendo, concluída, etc.).", tooltip_short: "Seu status de leitura." },
  chapters_total: { full: "Capítulos totais", short: "Capítulos", abbrev: "Caps.", tooltip_full: "Número total de capítulos da obra, quando conhecido.", tooltip_short: "Total de capítulos." },
  chapters_read: { full: "Capítulos lidos", short: "Lidos", abbrev: "Lidos", tooltip_full: "Quantos capítulos você já marcou como lidos.", tooltip_short: "Capítulos que você leu." },
  chapters_progress: { full: "Progresso de leitura", short: "% lido", abbrev: "% Lido", tooltip_full: "Progresso de leitura: capítulos lidos ÷ total de capítulos.", tooltip_short: "Capítulos lidos ÷ total." },
  year: { full: "Ano de lançamento", short: "Ano", abbrev: "Ano", tooltip_full: "Ano de lançamento/início da publicação.", tooltip_short: "Ano de lançamento." },
  ai_status: { full: "Status da avaliação IA", short: "Avaliação IA", abbrev: "IA", tooltip_full: "Estágio da avaliação por IA: pendente de atributos, pendente de Veredito IA, avaliado ou pulado.", tooltip_short: "Estágio da avaliação por IA." },
  updated_at: { full: "Atualizado em", short: "Atualizado", abbrev: "Atual.", tooltip_full: "Quando o registro da obra foi atualizado pela última vez.", tooltip_short: "Última atualização do registro." },
  last_read_at: { full: "Última leitura", short: "Última leitura", abbrev: "Últ. leit.", tooltip_full: "Data da última vez que você leu algum capítulo desta obra.", tooltip_short: "Sua última leitura." },
} as const

export type LabelField = keyof typeof LABELS
