-- External rating sources available in the manual source dropdown.
CREATE TABLE IF NOT EXISTS source (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  name       TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS source_name_lower_idx
  ON source (lower(name));

INSERT INTO source (name)
SELECT value
FROM (VALUES
  ('ComicK'),
  ('Anime Planet'),
  ('Manga Updates'),
  ('AniList'),
  ('Comix')
) AS seed(value)
WHERE NOT EXISTS (
  SELECT 1 FROM source WHERE lower(source.name) = lower(seed.value)
);
